### ISSUE TITLE
duplicate refresh requests when using controller on multiple views

### ISSUE THREAD

**Issue by clragon** [EdsonBueno/infinite_scroll_pagination#148]
The information in this comment are outdated.
Please see the comments further down for a comprehensive issue description.

----

I have run into the curious issue that any `PagedView` that receives a `refresh` call 
but isnt the top most route will call the `requestPage` callback twice in a row.

I have laced my code with extensive debug logs because it was impossible to breakpoint it.

heres what the log looks like:

`#5c79c` is the very first (root) route.
`#6d0c2` is the middle route.
`#8a43b` is the top (current) route.

```yaml
Performing hot reload...
Syncing files to device Windows...
Reloaded 145 of 1439 libraries in 2’413ms.
flutter: [#5c79c] instantiated!
flutter: [#5c79c] started waiting for a request page!
flutter: [#5c79c] loading page 1
flutter: [#5c79c] appending a new page of length 70
flutter: [#5c79c] providing a next page key: 2
flutter: [#5c79c] done requesting and adding page, releasing lock!
flutter: [#6d0c2] instantiated!
flutter: [#6d0c2] started waiting for a request page!
flutter: [#6d0c2] loading page 1
flutter: [#6d0c2] appending a new page of length 73
flutter: [#6d0c2] providing a next page key: 2
flutter: [#6d0c2] done requesting and adding page, releasing lock!
flutter: [#8a43b] instantiated!
flutter: [#8a43b] started waiting for a request page!
flutter: [#8a43b] loading page 1
flutter: [#8a43b] appending a new page of length 70
flutter: [#8a43b] providing a next page key: 2
flutter: [#8a43b] done requesting and adding page, releasing lock!
flutter: [#5c79c] triggered refresh by ValueNotifier<String>#515e8
flutter: [#5c79c] allowed a refresh!
flutter: [#6d0c2] triggered refresh by ValueNotifier<String>#515e8
flutter: [#6d0c2] allowed a refresh!
flutter: [#8a43b] triggered refresh by ValueNotifier<String>#515e8
flutter: [#8a43b] allowed a refresh!
flutter: [#5c79c] resetting posts now!
flutter: [#5c79c] allowed a refresh!
flutter: [#6d0c2] resetting posts now!
flutter: [#6d0c2] allowed a refresh!
flutter: [#8a43b] resetting posts now!
flutter: [#8a43b] allowed a refresh!
flutter: [#5c79c] calling super.refresh!
flutter: [#5c79c] started waiting for a request page!
flutter: [#5c79c] started waiting for a request page!
flutter: [#6d0c2] calling super.refresh!
flutter: [#6d0c2] started waiting for a request page!
flutter: [#6d0c2] started waiting for a request page!
flutter: [#8a43b] calling super.refresh!
flutter: [#8a43b] started waiting for a request page!
flutter: [#5c79c] loading page 1
flutter: [#6d0c2] loading page 1
flutter: [#8a43b] loading page 1
flutter: [#6d0c2] appending a new page of length 7
flutter: [#6d0c2] providing a next page key: 2
flutter: [#6d0c2] done requesting and adding page, releasing lock!
flutter: [#6d0c2] loading page 1
flutter: [#6d0c2] started waiting for a request page!
flutter: [#5c79c] appending a new page of length 79
flutter: [#5c79c] providing a next page key: 2
flutter: [#5c79c] done requesting and adding page, releasing lock!
flutter: [#5c79c] loading page 1
flutter: [#8a43b] appending a new page of length 80
flutter: [#8a43b] providing a next page key: 2
flutter: [#8a43b] done requesting and adding page, releasing lock!
flutter: [#6d0c2] appending a new page of length 7
flutter: [#6d0c2] providing a next page key: 2
flutter: [#6d0c2] done requesting and adding page, releasing lock!
flutter: [#6d0c2] loading page 2
flutter: [#6d0c2] started waiting for a request page!
flutter: [#6d0c2] done requesting and adding page, releasing lock!
flutter: [#6d0c2] loading page 2
flutter: [#5c79c] appending a new page of length 79
flutter: [#5c79c] providing a next page key: 2
flutter: [#5c79c] done requesting and adding page, releasing lock!
flutter: [#6d0c2] done requesting and adding page, releasing lock!
flutter: [#8a43b] banished to the shadow realm!
flutter: [#6d0c2] banished to the shadow realm!
```

in the log you can see that both routes that are not at the top, `#5c79c` and `#6d0c2` get two requests for loading a new page.
said two requests are issued exactly at the same time.
In my code I use mutex locks to prevent multiple requests from ever running at the same time, 
so those 2 requests are ran after each other, but theyre still ran with the same page key.

I have also printed the stack trace logs and made sure that it is not my code that is triggering multiple refresh requests.
In the log above, you can see how my linked `valuenotifier` is only ever triggering a single request.

You can also see how the top most route, `#8a43b` only triggers a single refresh request.

this issue also occurs on android and it happens exactly the same everytime.
I have also tested this with only a single route at the bottom, said route will still receive two refresh requests.

I am using version `4.0.0` on 268945f (because I would like to use the staggered grid and page view paged variants).

My code for using the `PagingController` is rather complicated but I doubt it is the cause of this issue, 
regardless, it could be found here:

- [general implementation](https://github.com/clragon/e1547/blob/master/lib/interface/data/controller.dart)
- [specific implementation](https://github.com/clragon/e1547/blob/master/lib/post/data/controller.dart)
